/**
 * VS Code language ID → file extensions / fileNames.
 *
 * Sourced from VS Code built-in language extensions
 * (microsoft/vscode/extensions/<lang>/package.json `contributes.languages`)
 * plus the popular third-party extensions referenced by
 * material-icon-theme's `languageIcons.ts`.
 *
 * Extensions are stored WITHOUT the leading dot, lowercase.
 * fileNames are stored as-is (case is preserved; consumer lowercases).
 */

export type LanguageIdAssoc = {
	extensions?: string[];
	fileNames?: string[];
};

export const languageIdAssociations: Record<string, LanguageIdAssoc> = {
	// --- VS Code built-ins ---
	bat: { extensions: ["bat", "cmd"] },
	clojure: { extensions: ["clj", "cljs", "cljc", "cljx", "clojure", "edn"] },
	coffeescript: { extensions: ["coffee", "cson", "iced"] },
	c: { extensions: ["c", "i"] },
	cpp: {
		extensions: [
			"cpp",
			"cc",
			"cxx",
			"c++",
			"hpp",
			"hh",
			"hxx",
			"h++",
			"mm",
			"ino",
			"inl",
			"ipp",
			"ixx",
			"tpp",
			"txx",
			"cppm",
			"ccm",
			"cxxm",
			"c++m",
		],
	},
	csharp: { extensions: ["cs", "csx", "cake"] },
	css: { extensions: ["css"] },
	diff: {
		extensions: ["diff", "patch", "rej"],
	},
	dockerfile: {
		extensions: ["dockerfile", "containerfile"],
		fileNames: ["Dockerfile", "Containerfile"],
	},
	dockercompose: {
		fileNames: [
			"compose.yaml",
			"compose.yml",
			"docker-compose.yaml",
			"docker-compose.yml",
			"docker-compose.ci.yml",
			"docker-compose.override.yml",
			"docker-compose.vs.debug.yml",
			"docker-compose.vs.release.yml",
			"docker-compose.dev.yml",
			"docker-compose.local.yml",
			"docker-compose.prod.yml",
			"docker-compose.production.yml",
			"docker-compose.staging.yml",
			"docker-compose.test.yml",
		],
	},
	fsharp: { extensions: ["fs", "fsi", "fsx", "fsscript"] },
	"git-commit": { fileNames: ["COMMIT_EDITMSG", "MERGE_MSG"] },
	"git-rebase": { fileNames: ["git-rebase-todo"] },
	go: { extensions: ["go"] },
	groovy: {
		extensions: ["groovy", "gvy", "gradle", "jenkinsfile", "nf"],
		fileNames: ["Jenkinsfile"],
	},
	handlebars: { extensions: ["handlebars", "hbs", "hjs"] },
	hlsl: {
		extensions: [
			"hlsl",
			"hlsli",
			"fx",
			"fxh",
			"vsh",
			"psh",
			"cginc",
			"compute",
		],
	},
	html: {
		extensions: [
			"html",
			"htm",
			"shtml",
			"xhtml",
			"xht",
			"mdoc",
			"jsp",
			"asp",
			"aspx",
			"jshtm",
			"volt",
			"ejs",
			"rhtml",
		],
	},
	ini: { extensions: ["ini"] },
	properties: {
		extensions: [
			"properties",
			"cfg",
			"conf",
			"directory",
			"gitattributes",
			"gitconfig",
			"gitmodules",
			"editorconfig",
			"npmrc",
		],
		fileNames: [
			".env",
			".env.dev",
			".env.development",
			".env.prod",
			".env.production",
			".env.test",
			".env.local",
			".gitattributes",
			".gitconfig",
			".gitmodules",
			".editorconfig",
		],
	},
	java: { extensions: ["java", "jav"] },
	javascript: {
		extensions: ["js", "es6", "mjs", "cjs", "pac"],
		fileNames: ["jakefile"],
	},
	javascriptreact: { extensions: ["jsx"] },
	json: {
		extensions: [
			"json",
			"bowerrc",
			"jscsrc",
			"webmanifest",
			"js.map",
			"css.map",
			"ts.map",
			"har",
			"jslintrc",
			"jsonld",
			"geojson",
			"ipynb",
			"vuerc",
		],
		fileNames: ["composer.lock", ".watchmanconfig"],
	},
	jsonc: {
		extensions: [
			"jsonc",
			"eslintrc",
			"eslintrc.json",
			"jshintrc",
			"swcrc",
			"hintrc",
			"babelrc",
		],
		fileNames: [
			".eslintrc",
			".eslintrc.json",
			".jsfmtrc",
			".jshintrc",
			".swcrc",
			".hintrc",
			".babelrc",
		],
	},
	json5: { extensions: ["json5"] },
	jsonl: { extensions: ["jsonl", "ndjson"] },
	julia: { extensions: ["jl"] },
	juliamarkdown: { extensions: ["jmd"] },
	less: { extensions: ["less"] },
	log: { extensions: ["log"] },
	lua: { extensions: ["lua"] },
	makefile: {
		extensions: ["mak", "mk"],
		fileNames: ["Makefile", "makefile", "GNUmakefile", "OCamlMakefile"],
	},
	markdown: {
		extensions: [
			"md",
			"mkd",
			"mdwn",
			"mdown",
			"markdown",
			"markdn",
			"mdtxt",
			"mdtext",
			"workbook",
		],
	},
	"objective-c": { extensions: ["m"] },
	"objective-cpp": { extensions: ["mm"] },
	perl: { extensions: ["pl", "pm", "pod", "t", "PL", "psgi"] },
	perl6: {
		extensions: [
			"raku",
			"rakumod",
			"rakutest",
			"rakudoc",
			"nqp",
			"p6",
			"pl6",
			"pm6",
		],
	},
	php: {
		extensions: ["php", "php4", "php5", "phtml", "ctp"],
	},
	plaintext: { extensions: ["txt", "text", "gyp", "gypi"] },
	powershell: {
		extensions: ["ps1", "psm1", "psd1", "pssc", "psrc"],
	},
	pug: { extensions: ["pug", "jade"] },
	python: {
		extensions: ["py", "rpy", "pyw", "cpy", "gyp", "gypi", "pyi", "ipy", "pyt"],
		fileNames: ["SConstruct", "SConscript"],
	},
	r: { extensions: ["r", "rhistory", "rprofile", "rt"] },
	razor: { extensions: ["cshtml", "razor"] },
	ruby: {
		extensions: [
			"rb",
			"rbi",
			"rbx",
			"rjs",
			"gemspec",
			"rake",
			"ru",
			"erb",
			"podspec",
			"rbprc",
		],
		fileNames: [
			"rakefile",
			"gemfile",
			"guardfile",
			"podfile",
			"capfile",
			"Rakefile",
			"Gemfile",
			"Guardfile",
			"Podfile",
			"Capfile",
		],
	},
	rust: { extensions: ["rs"] },
	scss: { extensions: ["scss"] },
	shaderlab: { extensions: ["shader"] },
	shellscript: {
		extensions: [
			"sh",
			"bash",
			"bashrc",
			"bash_aliases",
			"bash_profile",
			"bash_login",
			"ebuild",
			"profile",
			"osh",
			"xprofile",
			"xsession",
			"xsessionrc",
			"yash_profile",
			"yashrc",
			"zsh",
			"zshenv",
			"zlogin",
			"zlogout",
			"zprofile",
			"zshrc",
			"ksh",
			"csh",
			"cshrc",
			"tcshrc",
			"tcsh",
			"yash",
			"command",
		],
		fileNames: [
			".bashrc",
			".bash_aliases",
			".bash_profile",
			".bash_login",
			".profile",
			".zshrc",
			".zshenv",
			".zlogin",
			".zlogout",
			".zprofile",
			".kshrc",
			".cshrc",
			".tcshrc",
			"APKBUILD",
			"PKGBUILD",
		],
	},
	sql: { extensions: ["sql", "dsql"] },
	swift: { extensions: ["swift"] },
	"search-result": { extensions: ["code-search"] },
	typescript: { extensions: ["ts", "cts", "mts"] },
	typescriptreact: { extensions: ["tsx"] },
	vb: { extensions: ["vb", "brs", "vbs", "bas", "vba"] },
	xml: {
		extensions: [
			"xml",
			"xsd",
			"ascx",
			"atom",
			"axml",
			"axaml",
			"bpmn",
			"cpt",
			"csl",
			"csproj",
			"csproj.user",
			"dita",
			"ditamap",
			"dtd",
			"ent",
			"mod",
			"dtml",
			"fsproj",
			"fxml",
			"iml",
			"isml",
			"jmx",
			"launch",
			"menu",
			"mxml",
			"nuspec",
			"opml",
			"owl",
			"proj",
			"props",
			"pt",
			"publishsettings",
			"pubxml",
			"pubxml.user",
			"rbxlx",
			"rbxmx",
			"rdf",
			"rng",
			"rngs",
			"rss",
			"rss2",
			"shproj",
			"storyboard",
			"targets",
			"tld",
			"tmx",
			"vbproj",
			"vbproj.user",
			"vcxproj",
			"vcxproj.filters",
			"wsdl",
			"wxi",
			"wxl",
			"wxs",
			"xaml",
			"xbl",
			"xib",
			"xlf",
			"xliff",
			"xpdl",
			"xul",
			"xoml",
		],
	},
	xsl: { extensions: ["xsl", "xslt"] },
	yaml: {
		extensions: ["yml", "yaml", "eyaml", "eyml", "cff", "cita", "gemfileyaml"],
	},

	// --- Common third-party language extensions ---
	ansible: { extensions: ["ansible"] },
	"ansible-jinja": { extensions: ["j2", "jinja2", "jinja", "njk"] },
	apex: { extensions: ["cls", "apex", "trigger"] },
	aspnetcorerazor: { extensions: ["cshtml", "razor"] },
	apiblueprint: { extensions: ["apib", "apiblueprint"] },
	applescript: { extensions: ["applescript"] },
	autoit: { extensions: ["au3"] },
	awk: { extensions: ["awk", "gawk", "mawk", "nawk"] },
	beancount: { extensions: ["beancount", "bean"] },
	bibtex: { extensions: ["bib"] },
	"bibtex-style": { extensions: ["bst"] },
	blink: { extensions: ["b"] },
	c3: { extensions: ["c3", "c3i", "c3t"] },
	cabal: { extensions: ["cabal"], fileNames: ["cabal.project"] },
	cake: { extensions: ["cake"] },
	cadence: { extensions: ["cdc"] },
	capnb: { extensions: ["capnb"] },
	cds: { extensions: ["cds"] },
	"cds-markdown-injection": {},
	concourse: { extensions: ["cpipeline", "ctask"] },
	"concourse-pipeline-yaml": {},
	"concourse-task-yaml": {},
	context: { extensions: ["mkii", "mkiv", "mkvi", "mkxl", "mklx"] },
	csv: { extensions: ["csv"] },
	cucumber: { extensions: ["feature"] },
	cue: { extensions: ["cue"] },
	dart: { extensions: ["dart"] },
	dhall: { extensions: ["dhall"] },
	"django-html": { extensions: ["djhtml"] },
	"django-txt": { extensions: ["djtxt"] },
	dockerbake: { fileNames: ["docker-bake.hcl", "docker-bake.json"] },
	doctex: { extensions: ["dtx"] },
	"doctex-installer": { extensions: ["ins"] },
	editorconfig: { fileNames: [".editorconfig"] },
	elixir: { extensions: ["ex", "exs", "eex", "leex", "heex", "neex", "sface"] },
	elm: { extensions: ["elm"] },
	erlang: { extensions: ["erl", "hrl", "escript"] },
	ets: { extensions: ["ets"] },
	gdresource: { extensions: ["tres", "tscn", "godot", "gdns", "gdnlib"] },
	gdscript: { extensions: ["gd"] },
	gdshader: { extensions: ["gdshader", "gdshaderinc"] },
	gemini: { extensions: ["gmi", "gemini"] },
	"text-gemini": { extensions: ["gmi"] },
	git: {
		extensions: [
			"gitignore",
			"gitkeep",
			"gitattributes",
			"gitmodules",
			"gitconfig",
		],
	},
	"github-actions-workflow": {},
	glsl: {
		extensions: [
			"glsl",
			"vs",
			"fs",
			"gs",
			"vert",
			"tesc",
			"tese",
			"frag",
			"geom",
			"comp",
		],
	},
	gnuplot: { extensions: ["gp", "gnu", "gnuplot", "plt", "plot"] },
	grain: { extensions: ["gr"] },
	graphql: { extensions: ["graphql", "gql"] },
	hack: { extensions: ["hack", "hh", "hhi"] },
	haml: { extensions: ["haml"] },
	haskell: { extensions: ["hs", "lhs"] },
	haxe: { extensions: ["hx"] },
	hxml: { extensions: ["hxml"] },
	hcl: { extensions: ["hcl"] },
	helm: {
		extensions: ["tpl"],
		fileNames: ["Chart.yaml", "Chart.lock", "values.yaml"],
	},
	hjson: { extensions: ["hjson"] },
	hosts: { fileNames: ["hosts", "HOSTS"] },
	huff: { extensions: ["huff"] },
	idris: { extensions: ["idr", "lidr"] },
	jade: { extensions: ["jade", "pug"] },
	ignore: {
		extensions: ["gitignore", "npmignore", "dockerignore"],
		fileNames: [".gitignore", ".npmignore", ".dockerignore"],
	},
	instructions: { extensions: ["instructions.md"] },
	jinja: { extensions: ["jinja"] },
	jupyter: { extensions: ["ipynb"] },
	kql: { extensions: ["kql", "csl"] },
	"lang-cfml": { extensions: ["cfml", "cfm", "cfc"] },
	latex: { extensions: ["tex", "ltx", "ctx", "sty", "cls"] },
	"latex-class": { extensions: ["cls"] },
	"latex-expl3": {},
	"latex-package": { extensions: ["sty"] },
	lean: { extensions: ["lean", "olean"] },
	livescript: { extensions: ["ls"] },
	lolcode: { extensions: ["lol"] },
	luau: { extensions: ["luau"] },
	markdoc: { extensions: ["mdoc"] },
	matlab: { extensions: ["m"] },
	mcfunction: { extensions: ["mcfunction"] },
	mjml: { extensions: ["mjml"] },
	mojo: { extensions: ["mojo", "🔥"] },
	nginx: {
		fileNames: ["nginx.conf", "nginx.conf.template"],
		extensions: ["nginx"],
	},
	nim: { extensions: ["nim", "nims"] },
	nimble: { extensions: ["nimble"] },
	nix: { extensions: ["nix"] },
	"ng-template": { extensions: ["ng-template"] },
	nunjucks: { extensions: ["njk", "nunjucks"] },
	otne: { extensions: ["otne"] },
	opentofu: { extensions: ["tofu"] },
	pawn: { extensions: ["pwn", "inc"] },
	pdf: { extensions: ["pdf"] },
	pgn: { extensions: ["pgn"] },
	"pip-requirements": {
		fileNames: [
			"requirements.txt",
			"requirements-dev.txt",
			"requirements-test.txt",
			"constraints.txt",
		],
	},
	postcss: { extensions: ["pcss", "postcss"] },
	processing: { extensions: ["pde"] },
	prolog: { extensions: ["pro", "pl"] },
	proto: { extensions: ["proto"] },
	psv: { extensions: ["psv"] },
	puppet: { extensions: ["pp", "epp"] },
	purescript: { extensions: ["purs"] },
	reason: { extensions: ["re", "rei"] },
	reason_lisp: {},
	rescript: { extensions: ["res", "resi"] },
	riot: { extensions: ["tag"] },
	robotframework: { extensions: ["robot", "resource"] },
	rsweave: { extensions: ["rnw", "snw", "rtex"] },
	salesforce: { extensions: ["cls", "trigger"] },
	sas: { extensions: ["sas"] },
	sass: { extensions: ["sass"] },
	scala: { extensions: ["scala", "sbt", "sc"] },
	skill: { extensions: ["il", "ils", "cdsenv", "cdsinit"] },
	slim: { extensions: ["slim"] },
	slint: { extensions: ["slint", "60"] },
	sml: { extensions: ["sml", "sig", "fun", "cm"] },
	solidity: { extensions: ["sol"] },
	"spring-boot-properties": {
		fileNames: [
			"application.properties",
			"application-dev.properties",
			"application-prod.properties",
			"application-test.properties",
		],
	},
	"spring-boot-properties-yaml": {
		fileNames: [
			"application.yml",
			"application.yaml",
			"application-dev.yml",
			"application-dev.yaml",
			"application-prod.yml",
			"application-prod.yaml",
			"application-test.yml",
			"application-test.yaml",
		],
	},
	ssh_config: {
		fileNames: ["ssh_config", ".ssh/config", "sshd_config"],
		extensions: ["ssh_config"],
	},
	stylable: { extensions: ["st.css"] },
	stylus: { extensions: ["styl"] },
	svelte: { extensions: ["svelte"] },
	svg: { extensions: ["svg"] },
	"systemd-conf": { extensions: ["link", "netdev", "network"] },
	"systemd-unit-file": {
		extensions: [
			"automount",
			"device",
			"mount",
			"path",
			"scope",
			"service",
			"slice",
			"socket",
			"swap",
			"target",
			"timer",
		],
	},
	terraform: { extensions: ["tf", "tfvars"] },
	testOutput: {},
	tex: { extensions: ["tex"] },
	toml: { extensions: ["toml"] },
	tree: { extensions: ["tree"] },
	tsv: { extensions: ["tsv"] },
	"twee3-chapbook-1": {},
	"twee3-harlowe-3": {},
	"twee3-sugarcube-2": {},
	twee3: { extensions: ["tw", "twee"] },
	twig: { extensions: ["twig"] },
	v: { extensions: ["v", "vsh"] },
	viml: { extensions: ["vim", "vimrc", "gvimrc", "ideavimrc"] },
	vue: { extensions: ["vue"] },
	"vue-html": {},
	"vue-postcss": {},
	wgsl: { extensions: ["wgsl"] },
	wolfram: { extensions: ["wl", "wls", "m", "nb"] },
	xquery: { extensions: ["xq", "xql", "xqm", "xqy", "xquery"] },
	yang: { extensions: ["yang"] },
};
